### PR TITLE
Error corrections for Gender Shades

### PR DESCRIPTION
**Pull request by tgebru**
Timnit Gebru <tgebru@gmail.com>
	
AttachmentsMon, Feb 27, 3:11 PM
	
Dear PMLR staff, 

We found out that we swapped true positive rates (TPR) and positive predictive value (PPV), on tables 4 and 5 of our paper and table 2 of the supplementary materials. This also changed the false positive rate (FPR) calculations. The corrections need to be made on pages 9 and 10 of the main paper and page 2 of the supplementary materials. Nothing has changed about the conclusions about the paper or main results. We have received permission to update the paper from editors at the time, Sorelle Friedler and Christo Wilson. We received this permission on email on February 27, after we also sent the marked up version of the paper showing all the changes that will be made. I have attached here the updated paper and supplementary materials.

### CODE REVIEW

**Comment by lawrennd** [comment]
Thanks Timnit! Can you confirm you have volume editor's approval for the fix? A comment mentioning who the approval is from should suffice) and then I'll merge.

**Comment by tgebru** [comment]
Yes. We got approval from the editors on February 27. We told them exactly
what the errors were and sent them marked up versions of the papers to show
them the exact corrections.

**Comment by tgebru** [comment]
The approval was from Sorelle Friedler and Christo Wilson

**Comment by lawrennd** [comment]
Thanks!

**Comment by tgebru** [comment]
Thank you. When should I expect the changes to be reflected? Do I just see it in the old website? Sorry first time I'm making a correction to a paper (and 5 years later :))

**Comment by lawrennd** [comment]
It should just recompile on it's own, takes about 10 minutes for a larger proceedings, if you double check now the new paper should be in place (unless I missed something). Let me know if not!

**Review by lawrennd — COMMENTED** [review]
Whoops, actually I missed this change. I think only change you needed was a new pdf, but there's something funny here. the dat-parts field shouldn't change ... or did zi misunderstand?

**Comment by tgebru** [comment]
I get a 404 message when I go to the website:
https://proceedings.mlr.press/v81/buolamwini18a.html

The two pdfs needed are:
The updated paper:
https://github.com/mlresearch/v81/files/11081432/buolamwini18.pdf
The updated supplementary materials:
https://github.com/mlresearch/v81/files/11081434/buolamwini18-supp.pdf

**Comment by lawrennd** [comment]
The new files need to overwrite the previous versions. The old versions sit under the subdirectory buolamwini18a, it won't pick them up on these new locations.

Does that make sense?


Neil
--
Professor Neil Lawrence
http://inverseprobability.com
________________________________

**Comment by tgebru** [comment]
Oh that makes sense. I just did that on my fork. Sorry I should have
checked earlier. Should I create another pull request?

**Comment by lawrennd** [comment]
Yes please! Thanks, and sorry for not spotting before.

**Comment by lawrennd** [comment]
I've reverted this pull request here: https://github.com/mlresearch/v81/pull/6

If you do a new pull request we can use that. Sorry again for the mucking about!

**Comment by tgebru** [comment]
Oops sorry I created a new pull request without seeing this reverted one.
LMK if that's ok or creates problems. No worries. I should have asked
before.

**Pull request merged**
